# Generated by Django 4.0.3 on 2022-04-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merengon_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default='Descripción del producto', max_length=300),
            preserve_default=False,
        ),
    ]
